"""Add geographic coordinates and Zone/ODB models

Revision ID: d393279349b8
Revises: 001
Create Date: 2025-10-21 16:53:49.802827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd393279349b8'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gam_devices', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('gam_devices', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('gam_devices', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('gam_devices', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'gam_devices', 'zones', ['zone_id'], ['id'])
    op.add_column('subscribers', sa.Column('odb_splitter_id', sa.UUID(), nullable=True))
    op.add_column('subscribers', sa.Column('odb_port_number', sa.Integer(), nullable=True))
    op.add_column('subscribers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('subscribers', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'subscribers', 'odb_splitters', ['odb_splitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_column('subscribers', 'longitude')
    op.drop_column('subscribers', 'latitude')
    op.drop_column('subscribers', 'odb_port_number')
    op.drop_column('subscribers', 'odb_splitter_id')
    op.drop_constraint(None, 'gam_devices', type_='foreignkey')
    op.drop_column('gam_devices', 'zone_id')
    op.drop_column('gam_devices', 'address')
    op.drop_column('gam_devices', 'longitude')
    op.drop_column('gam_devices', 'latitude')
    # ### end Alembic commands ###
