"""Add SSH login fields to GAM devices

Revision ID: 6031547f8dde
Revises: d393279349b8
Create Date: 2025-10-21 17:54:52.518169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6031547f8dde'
down_revision: Union[str, None] = 'd393279349b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gam_devices', sa.Column('ssh_username', sa.String(length=100), nullable=True))
    op.add_column('gam_devices', sa.Column('ssh_password', sa.String(length=255), nullable=True))
    # Add ssh_port with server default, then remove the default
    op.add_column('gam_devices', sa.Column('ssh_port', sa.Integer(), nullable=False, server_default='22'))
    op.alter_column('gam_devices', 'ssh_port', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gam_devices', 'ssh_port')
    op.drop_column('gam_devices', 'ssh_password')
    op.drop_column('gam_devices', 'ssh_username')
    # ### end Alembic commands ###
